site_name: AfriMarket

theme:
  name: material
  icon:
    - annotation: material/arrow-right-circle
  features:
  - toc.follow
  - content.code.copy

  palette:
  # toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode

      # toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode


markdown_extensions:
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html